#!/bin/bash
# Stage 2 - BoltzGen epitope-conditioned binder design for both targets.
# Requires: GPU + BoltzGen install & weights (pip install boltzgen; see ../README.md).
# Configs are generated by make_boltzgen_config.py from the Stage-1 epitope.
set -euo pipefail

NUM_DESIGNS="${NUM_DESIGNS:-5000}"   # intermediate candidates
BUDGET="${BUDGET:-200}"              # final ranked designs kept

for T in NDM5 KPC3; do
  echo "=== BoltzGen: $T ==="
  boltzgen run "${T}_design.yaml" \
    --output "out_${T}" \
    --num_designs "${NUM_DESIGNS}" \
    --budget "${BUDGET}"
  # Output: out_${T}/final_ranked_designs/final_${BUDGET}_designs/  +  final_designs_metrics_${BUDGET}.csv
done
echo "Done. Convert designs to FASTA and feed Stage 3 (validation)."
